name: hoomd4GPU
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - attrs=24.2.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-version=12.4
  - debugpy=1.8.5
  - decorator=5.1.1
  - deprecation=2.1.0
  - embree=4.3.3
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.15.4
  - freetype=2.12.1
  - fresnel=0.13.6
  - freud=3.1.0
  - gsd=3.3.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hoomd=4.8.2
  - icu=75.1
  - importlib-metadata=8.6.1
  - importlib_resources=6.4.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurl=8.9.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnvjitlink=12.4.127
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mpi=1.0
  - mpi4py=4.0.0
  - mpich=4.2.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.0.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pygments=2.19.1
  - python=3.12.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.35.1
  - rowan=1.3.2
  - rpds-py=0.20.0
  - setuptools=72.1.0
  - signac=2.2.0
  - signac-flow=0.29.0
  - six=1.17.0
  - stack_data=0.6.3
  - synced_collections=1.0.0
  - tbb=2021.12.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - chex==0.1.88
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses==0.6
      - dm-haiku==0.0.13
      - e3nn-jax==0.20.7
      - einops==0.8.0
      - etils==1.11.0
      - flax==0.10.2
      - fonttools==4.55.3
      - frozendict==2.4.6
      - fsspec==2024.12.0
      - humanize==4.11.0
      - idna==3.10
      - jax==0.5.0
      - jax-cuda12-pjrt==0.5.0
      - jax-cuda12-plugin==0.5.0
      - jax-md==0.2.8
      - jaxlib==0.5.0
      - jmp==0.0.4
      - joblib==1.4.2
      - jraph==0.0.6.dev0
      - kiwisolver==1.4.8
      - latexcodec==3.0.0
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.4.0
      - monty==2025.1.9
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.6.0.22
      - nvidia-cuda-cupti-cu12==12.6.37
      - nvidia-cuda-nvcc-cu12==12.6.20
      - nvidia-cuda-runtime-cu12==12.6.37
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.6.28
      - nvidia-cusolver-cu12==11.6.4.38
      - nvidia-cusparse-cu12==12.5.2.23
      - nvidia-nccl-cu12==2.22.3
      - nvidia-nvjitlink-cu12==12.6.20
      - opt-einsum==3.3.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.0
      - palettable==3.3.3
      - pandas==2.2.3
      - pillow==11.1.0
      - plotly==5.24.1
      - protobuf==5.29.3
      - pybtex==0.24.0
      - pymatgen==2025.1.9
      - pyparsing==3.2.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - scipy==1.14.0
      - simplejson==3.19.3
      - spglib==2.5.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorstore==0.1.71
      - toolz==1.0.0
      - tzdata==2024.2
      - uncertainties==3.2.2
      - urllib3==2.3.0
